### ISSUE TITLE
Failed to create consumer binding; retrying in 30 seconds

### ISSUE THREAD

**Issue by vyom-soft** [Azure-Samples/azure-spring-boot-samples#44]
I followed the Spring Cloud Azure Stream Binder for Service Bus topic Sample shared library for Java.
While doing so and when the app is launched it throws : **Failed to create consumer binding; retrying in 30 seconds**

(https://github.com/Azure/azure-sdk-for-java/issues/24040)

`org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:462) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:91) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleConsumerBinding$1(BindingService.java:202) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.9.jar:5.3.9]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'exam-topic.tsubscription-one.errors.recoverer' defined in null: Cannot register bean definition [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'exam-topic.tsubscription-one.errors.recoverer': There is already [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:995) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:330) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.GenericApplicationContext.registerBean(GenericApplicationContext.java:478) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:687) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:639) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at com.azure.spring.servicebus.stream.binder.ServiceBusTopicMessageChannelBinder.createConsumerEndpoint(ServiceBusTopicMessageChannelBinder.java:49) ~[azure-spring-cloud-stream-binder-servicebus-topic-2.8.0.jar:na]
	at com.azure.spring.servicebus.stream.binder.ServiceBusTopicMessageChannelBinder.createConsumerEndpoint(ServiceBusTopicMessageChannelBinder.java:23) ~[azure-spring-cloud-stream-binder-servicebus-topic-2.8.0.jar:na]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:408) ~[spring-cloud-stream-3.1.3.jar:3.1.3]`

Here is the  application.yaml

spring:
  cloud:
    azure:
      servicebus:
        connection-string: [sb://vyom-broker.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=w1n+xtKl9Z9r0l0dyXk9tRq4K9GEi2pNGsS2L4yhUj2=]
    stream:
      bindings:
        consume-in-0:
          destination: exam-topic
          group: tsubscription-one
        supply-out-0:
          destination: exam-topic
      servicebus:
        topic:
          bindings:
            consume-in-0:
              consumer:
                checkpoint-mode: MANUAL
      function:
        definition: consume;supply;
      poller:
        fixed-delay: 1000
        initial-delay: 0
  autoconfigure:
    exclude: com.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusQueueAutoConfiguration
  profiles:
    active: manual

**Comment by backwind1233** [comment]
@vyom-soft thanks for your reply, 
@yiliuTo could you help look into this issue?

**Comment by backwind1233** [comment]
related with https://github.com/Azure/azure-sdk-for-java/issues/24040

**Comment by backwind1233** [comment]
close this issue, because it is tracked in https://github.com/Azure/azure-sdk-for-java/issues/24040
